export enum Icon {
  // General
  Home = 'mdi-home',
  Menu = 'mdi-menu',
  Close = 'mdi-close',
  Check = 'mdi-check',
  Delete = 'mdi-delete',
  Edit = 'mdi-pencil',
  Save = 'mdi-content-save',
  Search = 'mdi-magnify',
  Settings = 'mdi-cog',
  Info = 'mdi-information',
  Warning = 'mdi-alert',
  Error = 'mdi-alert-circle',
  Help = 'mdi-help-circle',
  Lightbulb = 'mdi-lightbulb',
  Power = 'mdi-power',
  Star = 'mdi-star',
  StarOutline = 'mdi-star-outline',
  StarHalf = 'mdi-star-half',

  // Navigation
  ArrowUp = 'mdi-arrow-up',
  ArrowDown = 'mdi-arrow-down',
  ArrowLeft = 'mdi-arrow-left',
  ArrowRight = 'mdi-arrow-right',
  ChevronUp = 'mdi-chevron-up',
  ChevronDown = 'mdi-chevron-down',
  ChevronLeft = 'mdi-chevron-left',
  ChevronRight = 'mdi-chevron-right',
  Expand = 'mdi-arrow-expand',
  Collapse = 'mdi-arrow-collapse',
  Refresh = 'mdi-refresh',

  // Social
  Facebook = 'mdi-facebook',
  Twitter = 'mdi-twitter',
  Instagram = 'mdi-instagram',
  LinkedIn = 'mdi-linkedin',
  GitHub = 'mdi-github',
  Google = 'mdi-google',
  YouTube = 'mdi-youtube',
  Reddit = 'mdi-reddit',
  WhatsApp = 'mdi-whatsapp',
  Slack = 'mdi-slack',

  // Media
  Play = 'mdi-play',
  Pause = 'mdi-pause',
  Stop = 'mdi-stop',
  VolumeUp = 'mdi-volume-high',
  VolumeDown = 'mdi-volume-low',
  VolumeMute = 'mdi-volume-off',
  MusicNote = 'mdi-music-note',
  Headphones = 'mdi-headphones',
  Microphone = 'mdi-microphone',
  MicrophoneOff = 'mdi-microphone-off',

  // User Interface
  Plus = 'mdi-plus',
  Minus = 'mdi-minus',
  Lock = 'mdi-lock',
  Unlock = 'mdi-lock-open',
  Eye = 'mdi-eye',
  EyeOff = 'mdi-eye-off',
  Filter = 'mdi-filter',
  Sort = 'mdi-sort',
  Copy = 'mdi-content-copy',
  Paste = 'mdi-content-paste',
  Cut = 'mdi-content-cut',
  Undo = 'mdi-undo',
  Redo = 'mdi-redo',
  Drag = 'mdi-drag',
  CheckCircle = 'mdi-check-circle',
  CloseCircle = 'mdi-close-circle',

  // Files and Folders
  File = 'mdi-file',
  Folder = 'mdi-folder',
  FolderOpen = 'mdi-folder-open',
  Upload = 'mdi-upload',
  Download = 'mdi-download',
  FileDocument = 'mdi-file-document',
  FilePdf = 'mdi-file-pdf',
  FileExcel = 'mdi-file-excel',
  FileWord = 'mdi-file-word',
  FileImage = 'mdi-file-image',
  FileVideo = 'mdi-file-video',
  FileMusic = 'mdi-file-music',
  FileArchive = 'mdi-file-archive',

  // Communication
  Email = 'mdi-email',
  Phone = 'mdi-phone',
  Message = 'mdi-message',
  Chat = 'mdi-chat',
  Comment = 'mdi-comment',
  Bell = 'mdi-bell',
  BellOff = 'mdi-bell-off',

  // E-commerce
  Cart = 'mdi-cart',
  CartOutline = 'mdi-cart-outline',
  CreditCard = 'mdi-credit-card',
  Cash = 'mdi-cash',
  Tag = 'mdi-tag',
  Barcode = 'mdi-barcode',
  Receipt = 'mdi-receipt',
  Sale = 'mdi-sale',

  // Weather
  WeatherSunny = 'mdi-weather-sunny',
  WeatherRainy = 'mdi-weather-rainy',
  WeatherCloudy = 'mdi-weather-cloudy',
  WeatherSnowy = 'mdi-weather-snowy',
  WeatherWindy = 'mdi-weather-windy',
  WeatherLightning = 'mdi-weather-lightning',

  // Transportation
  Car = 'mdi-car',
  Bike = 'mdi-bike',
  Bus = 'mdi-bus',
  Train = 'mdi-train',
  Airplane = 'mdi-airplane',
  Ship = 'mdi-ferry',

  // Health
  Heart = 'mdi-heart',
  HeartOutline = 'mdi-heart-outline',
  HeartPulse = 'mdi-heart-pulse',
  Hospital = 'mdi-hospital',
  Stethoscope = 'mdi-stethoscope',
  Pill = 'mdi-pill',
  Bandage = 'mdi-bandage',

  // Technology
  Computer = 'mdi-desktop-classic',
  Laptop = 'mdi-laptop',
  Tablet = 'mdi-tablet',
  PhoneAndroid = 'mdi-cellphone-android',
  Watch = 'mdi-watch',
  Keyboard = 'mdi-keyboard',
  Monitor = 'mdi-monitor',
  Printer = 'mdi-printer',
  Cloud = 'mdi-cloud',
  Server = 'mdi-server',

  // Miscellaneous
  Calendar = 'mdi-calendar',
  Clock = 'mdi-clock',
  Map = 'mdi-map',
  Camera = 'mdi-camera',
  Compass = 'mdi-compass',
  Key = 'mdi-key',
  LightSwitch = 'mdi-light-switch',
  TrashCan = 'mdi-trash-can',
  Shield = 'mdi-shield',
  ShieldCheck = 'mdi-shield-check',
}
